-- Generated by scripts/generate_postgres_seed_sql.py
-- system_id='braze-sdk-playground' tenant='kwt'
-- Default: Braze enabled, GA4 disabled (mapper versions set for future use).

-- system_catalog_configs (one row per catalog event for this system+tenant)
INSERT INTO system_catalog_configs (system_id, tenant, event_id, enabled, destinations) SELECT 'braze-sdk-playground', 'kwt', id, true, '{"braze": {"enabled": true, "mapper_version": "braze_track_v1"}, "ga4": {"enabled": false, "mapper_version": "ga4_mp_v1"}}'::jsonb FROM catalog_events ON CONFLICT (system_id, tenant, event_id) DO UPDATE SET enabled = EXCLUDED.enabled, destinations = EXCLUDED.destinations, updated_at = now();

