#!/usr/bin/env python3
"""
Generate batch SQL to seed Postgres from playground-events-catalog.normalized.json.

Outputs (under --out-dir):
  - 010_catalog_inserts.sql   — catalog_events + catalog_event_aliases
  - 020_system_config_inserts.sql — system_catalog_configs (Braze on, GA4 off by default)

Usage (from telemetry/):
  python scripts/generate_postgres_seed_sql.py \\
    --json .plan/playground-events-catalog.normalized.json \\
    --out-dir sql/seed \\
    --system-id braze-sdk-playground \\
    --tenant kwt

Apply:
  psql "$DATABASE_URL" -f sql/001_catalog_and_config.sql
  psql "$DATABASE_URL" -f sql/seed/010_catalog_inserts.sql
  psql "$DATABASE_URL" -f sql/seed/020_system_config_inserts.sql
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _telemetry_root() -> Path:
    p = Path(__file__).resolve()
    if p.parent.name == "scripts" and (p.parent.parent / "sql").is_dir():
        return p.parent.parent
    return Path.cwd()


def sql_literal(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def sql_json(obj: object) -> str:
    return sql_literal(json.dumps(obj, ensure_ascii=False))


def main() -> int:
    root = _telemetry_root()
    ap = argparse.ArgumentParser(description="Generate Postgres seed SQL from normalized catalog JSON.")
    ap.add_argument(
        "--json",
        type=Path,
        default=root / ".plan" / "playground-events-catalog.normalized.json",
        help="Path to playground-events-catalog.normalized.json",
    )
    ap.add_argument("--out-dir", type=Path, default=root / "sql" / "seed", help="Output directory")
    ap.add_argument("--system-id", default="braze-sdk-playground", help="system_id for system_catalog_configs")
    ap.add_argument("--tenant", default="kwt", help="tenant for system_catalog_configs (match meta.tenant in ingest)")
    ap.add_argument(
        "--truncate",
        action="store_true",
        help="Prepend TRUNCATE to clear catalog tables (dev only)",
    )
    args = ap.parse_args()

    path = args.json if args.json.is_absolute() else root / args.json
    if not path.is_file():
        print(f"Missing JSON: {path}", file=sys.stderr)
        return 1

    data = json.loads(path.read_text(encoding="utf-8"))
    events = data.get("events") or []

    out_dir = args.out_dir if args.out_dir.is_absolute() else root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    cat_file = out_dir / "010_catalog_inserts.sql"
    cfg_file = out_dir / "020_system_config_inserts.sql"

    dest_default = {
        "braze": {"enabled": True, "mapper_version": "braze_track_v1"},
        "ga4": {"enabled": False, "mapper_version": "ga4_mp_v1"},
    }

    lines_cat: list[str] = [
        "-- Generated by scripts/generate_postgres_seed_sql.py",
        f"-- source: {path.name}",
        f"-- events: {len(events)}",
        "",
    ]
    if args.truncate:
        lines_cat += [
            "TRUNCATE TABLE system_catalog_configs, catalog_event_aliases, catalog_events CASCADE;",
            "",
        ]

    lines_cat += [
        "-- catalog_events (idempotent)",
    ]

    for ev in events:
        canon = ev["canonical_name"]
        display = canon
        desc = f"Playground-derived; domain_tags={ev.get('domain_tags', [])}"
        meta = {
            "domain_tags": ev.get("domain_tags", []),
            "braze": ev.get("braze", {}),
            "ga4": ev.get("ga4", {}),
            "meta_standard_event_name": ev.get("meta_standard_event_name", False),
            "observed_in_playground_columns": ev.get("observed_in_playground_columns", {}),
        }
        lines_cat.append(
            "INSERT INTO catalog_events (canonical_name, display_name, description, lifecycle_status, catalog_metadata)"
            f" VALUES ({sql_literal(canon)}, {sql_literal(display)}, {sql_literal(desc)}, 'active', {sql_json(meta)}::jsonb)"
            " ON CONFLICT (canonical_name) DO UPDATE SET"
            " display_name = EXCLUDED.display_name,"
            " description = EXCLUDED.description,"
            " catalog_metadata = EXCLUDED.catalog_metadata,"
            " updated_at = now();"
        )

    lines_cat += ["", "-- catalog_event_aliases (skip if alias equals canonical_name)"]
    for ev in events:
        canon = ev["canonical_name"]
        for alias in ev.get("aliases") or []:
            if alias == canon:
                continue
            lines_cat.append(
                "INSERT INTO catalog_event_aliases (event_id, alias)"
                " SELECT id, "
                + sql_literal(alias)
                + " FROM catalog_events WHERE canonical_name = "
                + sql_literal(canon)
                + " ON CONFLICT (alias) DO NOTHING;"
            )

    cat_file.write_text("\n".join(lines_cat) + "\n", encoding="utf-8")

    lines_cfg: list[str] = [
        "-- Generated by scripts/generate_postgres_seed_sql.py",
        f"-- system_id={args.system_id!r} tenant={args.tenant!r}",
        "-- Default: Braze enabled, GA4 disabled (mapper versions set for future use).",
        "",
    ]
    if args.truncate:
        lines_cfg.append("TRUNCATE TABLE system_catalog_configs CASCADE;")
        lines_cfg.append("")

    lines_cfg.append("-- system_catalog_configs (one row per catalog event for this system+tenant)")
    dest_json = sql_json(dest_default)
    lines_cfg.append(
        "INSERT INTO system_catalog_configs (system_id, tenant, event_id, enabled, destinations)"
        f" SELECT {sql_literal(args.system_id)}, {sql_literal(args.tenant)}, id, true, {dest_json}::jsonb"
        " FROM catalog_events"
        " ON CONFLICT (system_id, tenant, event_id) DO UPDATE SET"
        " enabled = EXCLUDED.enabled,"
        " destinations = EXCLUDED.destinations,"
        " updated_at = now();"
    )
    lines_cfg.append("")

    cfg_file.write_text("\n".join(lines_cfg) + "\n", encoding="utf-8")

    print(f"Wrote {cat_file}")
    print(f"Wrote {cfg_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
